"""SQLModel tables for `control-db`.

**Read this before adding a column.** PRD §4 promises that the control plane
"structurally cannot hold conversation content or plaintext credentials". That is
enforced by `tests/test_privacy_schema.py`, which whitelists every column below.
Adding a `messages` table or a `dek` column breaks the build on purpose.

What *is* stored, and why it is allowed:
  * `Bot.token` -- a *Squire* pool-bot credential (ours, from BotFather), not the
    user's. control-api must hold it to call `setWebhook`.
  * `Bot.webhook_secret` -- generated by us, shared with ingress to authenticate
    Telegram callbacks.
  * `Tenant.email` -- the signup identifier. The only user PII here.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum

from sqlalchemy import BigInteger
from sqlmodel import Field, SQLModel


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class TenantStatus(str, Enum):
    """Values are part of the ingress interface contract -- do not rename."""

    PROVISIONING = "provisioning"
    RUNNING = "running"
    SLEEPING = "sleeping"  # Railway serverless sleep; ingress must still route+wake
    STOPPED = "stopped"  # deliberately halted (trial expiry, non-payment)
    DELETED = "deleted"  # service + volume destroyed (crypto-shred)


class BotStatus(str, Enum):
    AVAILABLE = "available"  # in the pool, unassigned
    ASSIGNED = "assigned"  # bound to a tenant
    DISABLED = "disabled"  # revoked/banned by Telegram, never hand out again


class ProvisionStep(str, Enum):
    """Explicit, ordered steps. `ProvisionJob.step` is always the *next* step to run.

    Ordering note: the task brief sketched `... -> set_variables -> deploy ->
    create_trial_key -> ...`. We create the trial key *before* set_variables because
    `ANTHROPIC_API_KEY` is one of the variables -- otherwise the tenant would boot
    without its trial key and need a second variable write plus a redeploy.
    """

    CREATE_SERVICE = "create_service"
    ATTACH_VOLUME = "attach_volume"
    CREATE_TRIAL_KEY = "create_trial_key"
    SET_VARIABLES = "set_variables"
    DEPLOY = "deploy"
    SET_WEBHOOK = "set_webhook"
    DONE = "done"


#: Execution order. `DONE` is terminal and has no handler.
PROVISION_STEP_ORDER: list[ProvisionStep] = [
    ProvisionStep.CREATE_SERVICE,
    ProvisionStep.ATTACH_VOLUME,
    ProvisionStep.CREATE_TRIAL_KEY,
    ProvisionStep.SET_VARIABLES,
    ProvisionStep.DEPLOY,
    ProvisionStep.SET_WEBHOOK,
    ProvisionStep.DONE,
]


class JobStatus(str, Enum):
    PENDING = "pending"  # more work to do (possibly after a backoff)
    RUNNING = "running"  # a worker holds it right now
    DONE = "done"
    FAILED = "failed"  # retries exhausted; needs a human


class Bot(SQLModel, table=True):
    """A BotFather bot from the pre-created pool (PRD §4 "Telegram bot supply")."""

    # Primary key IS the Telegram numeric bot id (the prefix of the token). That
    # makes the ingress hot-path lookup a primary-key hit.
    #
    # BigInteger, NOT plain int: Telegram now issues 10-digit bot ids (>2^31), and
    # SQLModel's `int` maps to a 32-bit INTEGER on Postgres. Registering a real
    # BotFather token failed live with psycopg NumericValueOutOfRange. SQLite has no
    # fixed-width integers so tests cannot catch this by behaviour -- the column
    # type is pinned by a model-inspection test instead
    # (tests/test_telegram_id_ranges.py). Telegram has also signalled that user/chat
    # ids may exceed 2^52, so BigInteger is the right floor for anything
    # Telegram-numeric, not a stopgap for today's 10 digits.
    # `autoincrement=False` because this id comes FROM Telegram -- we never generate
    # one. Without it SQLAlchemy sees an integer PK with no default and emits
    # BIGSERIAL, creating a sequence that is never advanced (harmless, but it
    # misrepresents where the id comes from and litters the schema).
    id: int = Field(
        primary_key=True,
        sa_type=BigInteger,
        sa_column_kwargs={"autoincrement": False},
    )
    token: str
    username: str
    status: BotStatus = Field(default=BotStatus.AVAILABLE, index=True)
    # Telegram `setWebhook.secret_token`; echoed back in X-Telegram-Bot-Api-Secret-Token.
    webhook_secret: str
    assigned_tenant_id: str | None = Field(default=None, index=True, unique=True)
    created_at: datetime = Field(default_factory=utcnow)


class Tenant(SQLModel, table=True):
    """One row per customer == one Railway service + one Railway volume."""

    id: str = Field(primary_key=True)
    email: str = Field(index=True, unique=True)
    status: TenantStatus = Field(default=TenantStatus.PROVISIONING, index=True)

    # Indexed because ingress resolves tenant-by-bot on every Telegram update.
    # BigInteger to match `Bot.id` -- a 32-bit FK pointing at a 64-bit PK would fail
    # to create the constraint on Postgres. See the note on `Bot.id`.
    bot_id: int | None = Field(
        default=None,
        foreign_key="bot.id",
        index=True,
        unique=True,
        sa_type=BigInteger,
    )

    # Mirror of Railway state (implementation-plan §1: "the placement table becomes
    # a mirror of Railway state").
    railway_service_id: str | None = None
    railway_service_name: str | None = None
    railway_volume_id: str | None = None

    # The container image reference control-api last set on this tenant's service.
    # This is the *desired* state; what the tenant actually reports running lives on
    # its `Heartbeat` row. The upgrade drill (infra/upgrade_drill.py) compares the
    # two to decide whether a canary really converged onto vN+1.
    image_ref: str | None = None

    # Private-network base URL ingress forwards to, e.g.
    # http://tenant-<id>.railway.internal:8080
    internal_url: str | None = None

    # A flag, never the key itself. The DEK lives only as a Railway service variable.
    dek_set: bool = False

    # We revoke trial keys *by alias* so the key material never enters this DB.
    trial_key_alias: str | None = None
    trial_key_active: bool = False

    webhook_set: bool = False

    created_at: datetime = Field(default_factory=utcnow)
    updated_at: datetime = Field(default_factory=utcnow)


class Heartbeat(SQLModel, table=True):
    """Latest self-reported state of one tenant container (Task 0.6).

    **Latest-state, not a time series.** One row per tenant, overwritten on every
    beat. A history table would be a slow-growing pile of per-tenant behavioural
    data in the control plane, which is precisely what PRD §4 says we do not keep;
    it would also need a retention policy nobody would remember to write. If we
    ever want trends, they belong in a metrics system outside the control DB.

    **Counts and gauges only.** Every column below is an integer, a boolean, or the
    image reference the container was handed. There is deliberately no room for a
    chat id, a message preview, an error string, or a free-form JSON blob -- the
    tenant is the only thing that sees conversation content, and the ingest schema
    (`schemas.HeartbeatRequest`, `extra="forbid"`) rejects anything else at the door.

    `updates_*` count Telegram *updates* the tenant's webhook shim handled, by
    outcome. They are cumulative since the container started, so they reset on every
    redeploy -- read them alongside `uptime_seconds`.
    """

    tenant_id: str = Field(primary_key=True, foreign_key="tenant.id")
    received_at: datetime = Field(default_factory=utcnow, index=True)

    # Seconds since the emitter started == roughly the container's age. A value that
    # went backwards is how you tell a tenant restarted between two beats.
    uptime_seconds: int = 0
    #: What the container says it is running (SQUIRE_IMAGE_REF, set at provision
    #: time and overwritten on redeploy). Compared against `Tenant.image_ref` to
    #: tell "we asked for vN+1" apart from "the tenant is running vN+1".
    image_ref: str | None = None

    gateway_up: bool = False
    hindsight_up: bool = False

    # Gauges for the G1 economics gate: RSS is container-wide (cgroup), the volume
    # figures come from statvfs on the mount.
    memory_rss_mb: int | None = None
    volume_used_mb: int | None = None
    volume_total_mb: int | None = None

    updates_forwarded: int | None = None
    updates_failed: int | None = None
    updates_rejected: int | None = None

    # Hindsight's async_operations queue depth, by status. None means the tenant
    # could not read its own memory DB -- distinct from "the queue is empty".
    hindsight_ops_pending: int | None = None
    hindsight_ops_processing: int | None = None
    hindsight_ops_failed: int | None = None

    # Seconds since the last SUCCESSFUL restic run, from a timestamp file the
    # backup script writes on the volume. None means "never succeeded, or backups
    # are not configured" -- which is every tenant today, since no B2 account
    # exists yet. A backup that quietly stopped working is invisible by nature, so
    # this is the number that makes it visible: on a healthy tenant it should
    # never exceed ~a day.
    backup_last_success_age_seconds: int | None = None


class ProvisionJob(SQLModel, table=True):
    """One provisioning run for one tenant. Re-runnable at any step."""

    id: str = Field(primary_key=True)
    tenant_id: str = Field(foreign_key="tenant.id", index=True)
    step: ProvisionStep = Field(default=ProvisionStep.CREATE_SERVICE)
    status: JobStatus = Field(default=JobStatus.PENDING, index=True)

    # Attempts are counted per-job, not per-step: a job that keeps failing anywhere
    # eventually stops burning Railway API quota.
    attempts: int = 0
    max_attempts: int = 5
    last_error: str | None = None

    # The worker only picks up jobs whose `next_attempt_at` is in the past.
    next_attempt_at: datetime = Field(default_factory=utcnow, index=True)

    created_at: datetime = Field(default_factory=utcnow)
    updated_at: datetime = Field(default_factory=utcnow)
