"""SQLModel tables for `control-db`.

**Read this before adding a column.** PRD §4 promises that the control plane
"structurally cannot hold conversation content or plaintext credentials". That is
enforced by `tests/test_privacy_schema.py`, which whitelists every column below.
Adding a `messages` table or a `dek` column breaks the build on purpose.

What *is* stored, and why it is allowed:
  * `Bot.token` -- a *Squire* pool-bot credential (ours, from BotFather), not the
    user's. control-api must hold it to call `setWebhook`.
  * `Bot.webhook_secret` -- generated by us, shared with ingress to authenticate
    Telegram callbacks.
  * `Tenant.email` -- the signup identifier. The only user PII here.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum

from sqlmodel import Field, SQLModel


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class TenantStatus(str, Enum):
    """Values are part of the ingress interface contract -- do not rename."""

    PROVISIONING = "provisioning"
    RUNNING = "running"
    SLEEPING = "sleeping"  # Railway serverless sleep; ingress must still route+wake
    STOPPED = "stopped"  # deliberately halted (trial expiry, non-payment)
    DELETED = "deleted"  # service + volume destroyed (crypto-shred)


class BotStatus(str, Enum):
    AVAILABLE = "available"  # in the pool, unassigned
    ASSIGNED = "assigned"  # bound to a tenant
    DISABLED = "disabled"  # revoked/banned by Telegram, never hand out again


class ProvisionStep(str, Enum):
    """Explicit, ordered steps. `ProvisionJob.step` is always the *next* step to run.

    Ordering note: the task brief sketched `... -> set_variables -> deploy ->
    create_trial_key -> ...`. We create the trial key *before* set_variables because
    `ANTHROPIC_API_KEY` is one of the variables -- otherwise the tenant would boot
    without its trial key and need a second variable write plus a redeploy.
    """

    CREATE_SERVICE = "create_service"
    ATTACH_VOLUME = "attach_volume"
    CREATE_TRIAL_KEY = "create_trial_key"
    SET_VARIABLES = "set_variables"
    DEPLOY = "deploy"
    SET_WEBHOOK = "set_webhook"
    DONE = "done"


#: Execution order. `DONE` is terminal and has no handler.
PROVISION_STEP_ORDER: list[ProvisionStep] = [
    ProvisionStep.CREATE_SERVICE,
    ProvisionStep.ATTACH_VOLUME,
    ProvisionStep.CREATE_TRIAL_KEY,
    ProvisionStep.SET_VARIABLES,
    ProvisionStep.DEPLOY,
    ProvisionStep.SET_WEBHOOK,
    ProvisionStep.DONE,
]


class JobStatus(str, Enum):
    PENDING = "pending"  # more work to do (possibly after a backoff)
    RUNNING = "running"  # a worker holds it right now
    DONE = "done"
    FAILED = "failed"  # retries exhausted; needs a human


class Bot(SQLModel, table=True):
    """A BotFather bot from the pre-created pool (PRD §4 "Telegram bot supply")."""

    # Primary key IS the Telegram numeric bot id (the prefix of the token). That
    # makes the ingress hot-path lookup a primary-key hit.
    id: int = Field(primary_key=True)
    token: str
    username: str
    status: BotStatus = Field(default=BotStatus.AVAILABLE, index=True)
    # Telegram `setWebhook.secret_token`; echoed back in X-Telegram-Bot-Api-Secret-Token.
    webhook_secret: str
    assigned_tenant_id: str | None = Field(default=None, index=True, unique=True)
    created_at: datetime = Field(default_factory=utcnow)


class Tenant(SQLModel, table=True):
    """One row per customer == one Railway service + one Railway volume."""

    id: str = Field(primary_key=True)
    email: str = Field(index=True, unique=True)
    status: TenantStatus = Field(default=TenantStatus.PROVISIONING, index=True)

    # Indexed because ingress resolves tenant-by-bot on every Telegram update.
    bot_id: int | None = Field(default=None, foreign_key="bot.id", index=True, unique=True)

    # Mirror of Railway state (implementation-plan §1: "the placement table becomes
    # a mirror of Railway state").
    railway_service_id: str | None = None
    railway_service_name: str | None = None
    railway_volume_id: str | None = None

    # Private-network base URL ingress forwards to, e.g.
    # http://tenant-<id>.railway.internal:8080
    internal_url: str | None = None

    # A flag, never the key itself. The DEK lives only as a Railway service variable.
    dek_set: bool = False

    # We revoke trial keys *by alias* so the key material never enters this DB.
    trial_key_alias: str | None = None
    trial_key_active: bool = False

    webhook_set: bool = False

    created_at: datetime = Field(default_factory=utcnow)
    updated_at: datetime = Field(default_factory=utcnow)


class ProvisionJob(SQLModel, table=True):
    """One provisioning run for one tenant. Re-runnable at any step."""

    id: str = Field(primary_key=True)
    tenant_id: str = Field(foreign_key="tenant.id", index=True)
    step: ProvisionStep = Field(default=ProvisionStep.CREATE_SERVICE)
    status: JobStatus = Field(default=JobStatus.PENDING, index=True)

    # Attempts are counted per-job, not per-step: a job that keeps failing anywhere
    # eventually stops burning Railway API quota.
    attempts: int = 0
    max_attempts: int = 5
    last_error: str | None = None

    # The worker only picks up jobs whose `next_attempt_at` is in the past.
    next_attempt_at: datetime = Field(default_factory=utcnow, index=True)

    created_at: datetime = Field(default_factory=utcnow)
    updated_at: datetime = Field(default_factory=utcnow)
